# Generated by Django 4.2.1 on 2024-04-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajay1', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
